USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;

-- >> GitHub Integrtion
------------------------------------------------------
CREATE OR REPLACE SECRET github_secret
  TYPE = PASSWORD
  USERNAME = '<USERNAME>'
  PASSWORD = '<PASSWORD>';

CREATE OR REPLACE API INTEGRATION github_api_int
  API_PROVIDER = git_https_api
  API_ALLOWED_PREFIXES = ('https://github.com/raysidharthamca')
  ALLOWED_AUTHENTICATION_SECRETS = (github_secret)
  ENABLED = TRUE;
------------------------------------------------------
-- << GitHub Integrtion


-- >> Sales Database Setup 
------------------------------------------------------
CREATE DATABASE SALES;

GRANT USAGE ON DATABASE SALES TO ROLE ACCOUNTADMIN;
GRANT USAGE ON ALL SCHEMAS IN DATABASE SALES TO ROLE ACCOUNTADMIN;

-- >> Copying Sales Tables 
------------------------------------------------------
CREATE OR REPLACE TABLE SALES.PUBLIC.CUSTOMER AS
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.CUSTOMER;

CREATE OR REPLACE TABLE SALES.PUBLIC.ORDERS AS
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.ORDERS;

CREATE OR REPLACE TABLE SALES.PUBLIC.LINEITEM AS
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.LINEITEM;

CREATE OR REPLACE TABLE SALES.PUBLIC.PART AS
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.PART;

CREATE OR REPLACE TABLE SALES.PUBLIC.PARTSUPP AS
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.PARTSUPP;

CREATE OR REPLACE TABLE SALES.PUBLIC.NATION AS
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.NATION;

CREATE OR REPLACE TABLE SALES.PUBLIC.REGION AS
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.REGION;
------------------------------------------------------
-- << Sales Database Setup 


-- >> Create Stage mystage 
------------------------------------------------------
create stage mystage;


-- >> SNOWFLAKE_INTELLIGENCE Database Setup 
------------------------------------------------------
CREATE DATABASE SNOWFLAKE_INTELLIGENCE;
USE DATABASE SNOWFLAKE_INTELLIGENCE;

CREATE SCHEMA AGENTS;
USE SCHEMA AGENTS;

GRANT USAGE ON DATABASE SNOWFLAKE_INTELLIGENCE TO ROLE ACCOUNTADMIN;
GRANT USAGE ON SCHEMA SNOWFLAKE_INTELLIGENCE.AGENTS TO ROLE ACCOUNTADMIN;
GRANT CREATE AGENT ON SCHEMA SNOWFLAKE_INTELLIGENCE.AGENTS TO ROLE ACCOUNTADMIN;
-- << SNOWFLAKE_INTELLIGENCE Database Setup 
------------------------------------------------------


ALTER ACCOUNT SET CORTEX_ENABLED_CROSS_REGION = 'AWS_US';